<a href="https://colab.research.google.com/github/acaicomdados/analise-reservatorios-federais/blob/main/An%C3%A1lise%20feito%20nos%20encontros/An%C3%A1lise%20s%C3%A9rie%20hist%C3%B3rica/Bacia%20Amazonas/Extraindo_serie_historica_amazonas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Extração das usinas relacionadas a bacia do amazonas

Neste notebook vão ser extraidas as series históricas referentes as bacias do amazonas, em qu vai ser feita a análise exploratória da mesma depois da bacia do tocantins

In [1]:
# blibioteca base dos dados
!pip install basedosdados

Requirement already satisfied: basedosdados in /usr/local/lib/python3.10/dist-packages (1.6.11)
Requirement already satisfied: Jinja2==3.0.3 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (3.0.3)
Requirement already satisfied: ckanapi==4.6 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (4.6)
Requirement already satisfied: click==8.0.3 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (8.0.3)
Requirement already satisfied: google-cloud-bigquery==2.30.1 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (2.30.1)
Requirement already satisfied: google-cloud-bigquery-storage==1.1.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (1.1.0)
Requirement already satisfied: google-cloud-storage==1.42.3 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (1.42.3)
Requirement already satisfied: importlib-metadata<5.0.0,>=4.11.3 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (4.13.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (0.6.0)
Requirement already satisfied: pandas<2.0.0,>=1.3.5 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (1.5.3)
Requirement already satisfied: pandas-gbq<0.18.0,>=0.17.4 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (0.17.9)
Requirement already satisfied: pandavro<2.0.0,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (1.8.0)
Requirement already satisfied: pyaml==20.4.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (20.4.0)
Requirement already satisfied: pyarrow==6.0.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (6.0.0)
Requirement already satisfied: ruamel.yaml==0.17.10 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (0.17.10)
Requirement already satisfied: shapely<2.0.0,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (1.8.5.post1)
Requirement already satisfied: toml<0.11.0,>=0.10.2 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (0.10.2)
Requirement already satisfied: tomlkit==0.7.0 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (0.7.0)
Requirement already satisfied: tqdm==4.50.2 in /usr/local/lib/python3.10/dist-packages (from basedosdados) (4.50.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from ckanapi==4.6->basedosdados) (71.0.4)
Requirement already satisfied: docopt in /usr/local/lib/python3.10/dist-packages (from ckanapi==4.6->basedosdados) (0.6.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from ckanapi==4.6->basedosdados) (2.32.3)
Requirement already satisfied: python-slugify>=1.0 in /usr/local/lib/python3.10/dist-packages (from ckanapi==4.6->basedosdados) (8.0.4)
Requirement already satisfied: six<2.0,>=1.9 in /usr/local/lib/python3.10/dist-packages (from ckanapi==4.6->basedosdados) (1.16.0)
Requirement already satisfied: grpcio<2.0dev,>=1.38.1 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.64.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=1.29.0 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery==2.30.1->basedosdados) (1.34.1)
Requirement already satisfied: proto-plus>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (1.24.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (2.4.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (2.7.2)
Requirement already satisfied: packaging>=14.3 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (24.1)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (3.20.3)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery==2.30.1->basedosdados) (2.8.2)
Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-storage==1.42.3->basedosdados) (2.27.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2==3.0.3->basedosdados) (2.1.5)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml==20.4.0->basedosdados) (6.0.2)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.10/dist-packages (from pyarrow==6.0.0->basedosdados) (1.26.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata<5.0.0,>=4.11.3->basedosdados) (3.20.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.0.0,>=1.3.5->basedosdados) (2024.1)
Requirement already satisfied: db-dtypes<2.0.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.3.0)
Requirement already satisfied: pydata-google-auth in /usr/local/lib/python3.10/dist-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.8.2)
Requirement already satisfied: google-auth-oauthlib>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.2.1)
Requirement already satisfied: fastavro<2.0.0,>=1.5.1 in /usr/local/lib/python3.10/dist-packages (from pandavro<2.0.0,>=1.6.0->basedosdados) (1.9.5)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core<3.0.0dev,>=1.29.0->google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery==2.30.1->basedosdados) (1.64.0)
Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery==2.30.1->basedosdados) (1.48.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from google-auth-oauthlib>=0.0.1->pandas-gbq<0.18.0,>=0.17.4->basedosdados) (1.3.1)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery==2.30.1->basedosdados) (1.5.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify>=1.0->ckanapi==4.6->basedosdados) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->ckanapi==4.6->basedosdados) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->ckanapi==4.6->basedosdados) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->ckanapi==4.6->basedosdados) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->ckanapi==4.6->basedosdados) (2024.7.4)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-cloud-storage==1.42.3->basedosdados) (0.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.0.1->pandas-gbq<0.18.0,>=0.17.4->basedosdados) (3.2.2)

In [14]:
import numpy as np
import pandas as pd
import basedosdados as bd
import plotly.express as px

In [3]:
url = 'https://raw.githubusercontent.com/acaicomdados/analise-reservatorios-federais/main/Datasets/reservatorio_geral_codigo_aneel.csv'

reservatorios = pd.read_csv(url)
reservatorios.drop('Unnamed: 0',axis=1,inplace=True)
reservatorios.head()

,data,subsistema,id_empreendimento_aneel,id_reservatorio_planejamento,id_posto_vazao,reservatorio_equivalente,reservatorio,tipo_reservatorio,usina,bacia,...,volume_util,produtividade_especifica,produtividade_65_volume_util,tipo_perda,perda_carga,latitude,longitude,sistema,codigo,estado_sigla
0,2007-02-03,SUL,UHE.PH.SC.027401-1.01,9,216,SUL,CAMPOS NOVOS,RESERVATORIO COM USINA,CAMPOS NOVOS,URUGUAI,...,129.62,0.009083,1.6063,m,2.48,-27.603056,-51.323611,sin,19068,SC
1,2005-11-01,SUL,UHE.PH.RS.027556-5.01,86,215,SUL,BARRA GRANDE,RESERVATORIO COM USINA,BARRA GRANDE,URUGUAI,...,2192.66,0.009218,1.4153,m,2.79,-27.777222,-51.188611,sin,19067,SC
2,2005-11-01,SUL,UHE.PH.RS.027556-5.01,86,215,SUL,BARRA GRANDE,RESERVATORIO COM USINA,BARRA GRANDE,URUGUAI,...,2192.66,0.009218,1.4153,m,2.79,-27.777222,-51.188611,sin,19067,RS
3,2013-09-24,SUL,UHE.PH.SC.030415-8.01,89,89,SUL,GARIBALDI,RESERVATORIO COM USINA,GARIBALDI,URUGUAI,...,64.23,0.008626,0.3691,m,1.19,-27.624722,-50.983889,sin,19147,SC
4,2002-02-16,SUL,UHE.PH.SC.001356-0.01,91,217,SUL,MACHADINHO,RESERVATORIO COM USINA,MACHADINHO,URUGUAI,...,1055.81,0.009034,0.8779,m,1.48,-27.524444,-51.788889,sin,19069,SC

In [4]:
reservatorios = reservatorios[['bacia','codigo','rio','estado_sigla']]
reservatorios.head()

     bacia  codigo      rio estado_sigla
0  URUGUAI   19068   CANOAS           SC
1  URUGUAI   19067  PELOTAS           SC
2  URUGUAI   19067  PELOTAS           RS
3  URUGUAI   19147   CANOAS           SC
4  URUGUAI   19069  URUGUAI           SC

In [5]:
serie_reseravtorios = bd.read_table(dataset_id='br_ana_reservatorios',
table_id='sin',
billing_project_id="558244945046")

Downloading: 100%|██████████| 1157621/1157621 [01:58<00:00, 9728.44rows/s]

In [6]:
serie_reseravtorios = serie_reseravtorios[['data','id_reservatorio','nome_reservatorio','afluencia']]
serie_reseravtorios.head()

         data id_reservatorio nome_reservatorio  afluencia
0  2000-01-01           19001          CAMARGOS     222.10
1  2000-01-02           19001          CAMARGOS     296.77
2  2000-01-03           19001          CAMARGOS     361.46
3  2000-01-04           19001          CAMARGOS     461.70
4  2000-01-05           19001          CAMARGOS     416.50

In [7]:
reservatorios.rename(columns={'codigo':'id_reservatorio'},inplace=True)
reservatorios['id_reservatorio'] = reservatorios['id_reservatorio'].astype(str)
reservatorios.head()

     bacia id_reservatorio      rio estado_sigla
0  URUGUAI           19068   CANOAS           SC
1  URUGUAI           19067  PELOTAS           SC
2  URUGUAI           19067  PELOTAS           RS
3  URUGUAI           19147   CANOAS           SC
4  URUGUAI           19069  URUGUAI           SC

In [8]:
serie_reseravtorios = serie_reseravtorios.merge(reservatorios,on='id_reservatorio')
serie_reseravtorios.head()

,data,id_reservatorio,nome_reservatorio,afluencia,bacia,rio,estado_sigla
0,2000-01-01,19001,CAMARGOS,222.10,GRANDE,GRANDE,MG
1,2000-01-02,19001,CAMARGOS,296.77,GRANDE,GRANDE,MG
2,2000-01-03,19001,CAMARGOS,361.46,GRANDE,GRANDE,MG
3,2000-01-04,19001,CAMARGOS,461.70,GRANDE,GRANDE,MG
4,2000-01-05,19001,CAMARGOS,416.50,GRANDE,GRANDE,MG

In [9]:
serie_historica_amazonas = serie_reseravtorios[serie_reseravtorios['bacia']=='AMAZONAS']
serie_historica_amazonas.head()

,data,id_reservatorio,nome_reservatorio,afluencia,bacia,rio,estado_sigla
1176966,2000-01-01,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
1176967,2000-01-03,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
1176968,2000-01-04,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
1176969,2000-01-05,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
1176970,2000-01-06,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO

In [11]:
serie_historica_amazonas['data'] = pd.to_datetime(serie_historica_amazonas['data'])
serie_historica_amazonas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 67140 entries, 1176966 to 1272541
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   data               67140 non-null  datetime64[ns]
 1   id_reservatorio    67140 non-null  object
 2   nome_reservatorio  67140 non-null  object
 3   afluencia          54719 non-null  float64
 4   bacia              67140 non-null  object
 5   rio                67140 non-null  object
 6   estado_sigla       67140 non-null  object
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 4.1+ MB

In [13]:
serie_historica_amazonas.reset_index(drop=True,inplace=True)
serie_historica_amazonas.head()

,data,id_reservatorio,nome_reservatorio,afluencia,bacia,rio,estado_sigla
0,2000-01-01,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
1,2000-01-03,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
2,2000-01-04,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
3,2000-01-05,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO
4,2000-01-06,19135,SANTO ANTONIO,NaN,AMAZONAS,MADEIRA,RO

In [16]:
serie_historica_amazonas.to_csv('serie_historica_amazonas.csv')